In [4]:
import numpy as np

In [15]:
data = np.loadtxt(open("train_2008.csv", "rb"), delimiter=",", skiprows=1)

In [17]:
X = data[:, 1:-1]
y = data[:, -1]

[[1.100e+01 2.008e+03 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.100e+01 2.008e+03 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.100e+01 2.008e+03 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [1.100e+01 2.008e+03 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.100e+01 2.008e+03 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.100e+01 2.008e+03 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]
[0. 0. 0. ... 0. 0. 0.]


In [22]:
N = len(y) #381
D = len(X[0]) #64667
train_size = 50000
train_X = X[:50000]
test_X = X[50000:]
train_y = y[:50000]
test_y = y[50000:]